services:
  db:
    image: postgres:17-alpine
    container_name: example_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example_sea_query
    volumes:
      - postgres_blog_tonic-data:/var/lib/postgresql/data
    networks:
      - app_blog_tonic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d example_sea_query"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: redis
    command: ["redis-server", "--requirepass", "dragon_knight"]
    ports:
      - "6379:6379"
    volumes:
      - redis_blog_tonic-data:/data
    restart: unless-stopped
    networks:
      - app_blog_tonic

  blog-client:
    image: ghcr.io/mamangrust/example-seaquery-tonic-grpc/blog-client:latest
    container_name: blog-client
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      otel-collector:
        condition: service_started
      blog-server:
        condition: service_started
    ports:
      - 5000:5000
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_blog_tonic

  blog-server:
    image: ghcr.io/mamangrust/example-seaquery-tonic-grpc/blog-server:latest
    container_name: blog-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 50051:50051
    depends_on:
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_blog_tonic

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-blog-tonic
    ports:
      - "16686:16686"       
      - "14250:14250"         
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - app_blog_tonic

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-tonic
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - app_blog_tonic

  prometheus:
    image: prom/prometheus
    container_name: prometheus-blog-tonic
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - app_blog_tonic

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-blog-tonic
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-blog-tonic-data:/var/lib/grafana 
    restart: unless-stopped
    networks:
      - app_blog_tonic

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-tonic
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "8889:8889"
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: unless-stopped
    networks:
      - app_blog_tonic


networks:
  app_blog_tonic:
    driver: bridge

volumes:
  grafana-blog-tonic-data:
  postgres_blog_tonic-data:
  redis_blog_tonic-data: